//
// Copyright (c) Vatsal Manot
//

@_spi(Internal) import Merge
@_spi(Internal) import Swallow
import SwiftUIX

public struct _ViewPrototypeConfiguration {
    public let anchor: _ViewPrototypeAnchor
}

public struct _AutogeneratedPrototypeContent: View {
    public var body: some View {
        Text("")
    }
}

/// A view that renders a `ViewPrototype`.
public struct Prototype<Content: View>: View {
    @_ViewBridge(_ViewPrototypeRenderBridge.self) private var parentRenderBridge: _ViewPrototypeRenderBridge

    public let configuration: _ViewPrototypeConfiguration
    public let content: Content?
    
    init(
        _configuration configuration: _ViewPrototypeConfiguration,
        content: Content
    ) {
        self.configuration = configuration
        self.content = content
    }
    
    public var body: some View {
        _UnimplementedView()
    }
}

struct PrototypeTests: View {
    var body: some View {
        Prototype(Label.self) {
            
        }
        
        Prototype(.button) {
            
        }
    }
}
